/* eslint-disable */
// Generated by Wrangler by running `wrangler types env.d.ts --include-runtime false` (hash: 236b87f0a4aff8945acc2b38f55ab6ee)
declare namespace Cloudflare {
  interface GlobalProps {
    mainModule: typeof import("./src/server");
    durableNamespaces: "ToDos";
  }
  interface Env {
    Todos: DurableObjectNamespace<import("./src/server").ToDos>;
  }
}
interface Env extends Cloudflare.Env {}
