/* eslint-disable */
// Generated by Wrangler by running `wrangler types env.d.ts --include-runtime false` (hash: 1ce144f2a62336e462f1668db705bd5f)
declare namespace Cloudflare {
  interface GlobalProps {
    mainModule: typeof import("./src/index");
    durableNamespaces: "MyServer";
  }
  interface Env {
    MyServer: DurableObjectNamespace<import("./src/index").MyServer>;
  }
}
interface Env extends Cloudflare.Env {}
