/* eslint-disable */
// Generated by Wrangler by running `wrangler types env.d.ts --include-runtime false` (hash: 4be7c89dd974cd4ea4cbcfd4e801b52e)
declare namespace Cloudflare {
  interface GlobalProps {
    mainModule: typeof import("./src/server");
    durableNamespaces: "Chat";
  }
  interface Env {
    Chat: DurableObjectNamespace<import("./src/server").Chat>;
  }
}
interface Env extends Cloudflare.Env {}
