/* eslint-disable */
// Generated by Wrangler by running `wrangler types env.d.ts --include-runtime false` (hash: 441b8bb0ef5bb12cd951148e37197291)
declare namespace Cloudflare {
  interface GlobalProps {
    mainModule: typeof import("./src/server");
    durableNamespaces: "Document";
  }
  interface Env {
    Document: DurableObjectNamespace<import("./src/server").Document>;
  }
}
interface Env extends Cloudflare.Env {}
