/* eslint-disable */
// Generated by Wrangler by running `wrangler types env.d.ts --include-runtime false` (hash: c2123e3b7970f87d90382ef4fbf1c18c)
declare namespace Cloudflare {
  interface GlobalProps {
    mainModule: typeof import("./src/server");
    durableNamespaces: "MonacoServer";
  }
  interface Env {
    Monaco: DurableObjectNamespace<import("./src/server").MonacoServer>;
  }
}
interface Env extends Cloudflare.Env {}
