/* eslint-disable */
// Generated by Wrangler by running `wrangler types env.d.ts --include-runtime false` (hash: 9d5eb238d4dbfdedf1bf7b0674d6a12c)
declare namespace Cloudflare {
  interface Env {
    RawAlarm: DurableObjectNamespace /* RawAlarm */;
    StockAlarm: DurableObjectNamespace /* StockAlarm */;
    FixedAlarm: DurableObjectNamespace /* FixedAlarm */;
  }
}
interface Env extends Cloudflare.Env {}
