/* eslint-disable */
// Generated by Wrangler by running `wrangler types env.d.ts --include-runtime false` (hash: 72fd07fb916987802dc1e04855905d6f)
declare namespace Cloudflare {
  interface GlobalProps {
    mainModule: typeof import("./src/server");
    durableNamespaces: "LexicalDocument";
  }
  interface Env {
    LexicalDocument: DurableObjectNamespace<
      import("./src/server").LexicalDocument
    >;
  }
}
interface Env extends Cloudflare.Env {}
