/* eslint-disable */
// Generated by Wrangler by running `wrangler types env.d.ts --include-runtime false` (hash: b44315135ddf33ad204297605c17acb5)
declare namespace Cloudflare {
  interface GlobalProps {
    mainModule: typeof import("./src/server");
    durableNamespaces: "MyServer";
  }
  interface Env {
    MyServer: DurableObjectNamespace<import("./src/server").MyServer>;
  }
}
interface Env extends Cloudflare.Env {}
