/* eslint-disable */
// Generated by Wrangler by running `wrangler types env.d.ts --include-runtime false` (hash: e295baf574e7d923e0ed9aff8fe52416)
declare namespace Cloudflare {
  interface GlobalProps {
    mainModule: typeof import("./src/server");
  }
  interface Env {
    REALTIME_SFU_APP_ID: string;
    REALTIME_SFU_APP_TOKEN: string;
    REALTIME_TURN_SERVER_APP_ID: string;
    REALTIME_TURN_SERVER_APP_TOKEN: string;
  }
}
interface Env extends Cloudflare.Env {}
