/* eslint-disable */
// Generated by Wrangler by running `wrangler types env.d.ts --include-runtime false` (hash: 8a9158374e5524d9d8082ee8c55b47aa)
declare namespace Cloudflare {
  interface GlobalProps {
    mainModule: typeof import("./src/server");
    durableNamespaces: "Globe";
  }
  interface Env {
    Globe: DurableObjectNamespace<import("./src/server").Globe>;
  }
}
interface Env extends Cloudflare.Env {}
