/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false env.d.ts`
interface __BaseEnv_Env {
  UserAgent: DurableObjectNamespace<import("./src/index").UserAgent>;
  ChatAgent: DurableObjectNamespace<import("./src/index").ChatAgent>;
}
declare namespace Cloudflare {
  interface GlobalProps {
    mainModule: typeof import("./src/index");
    durableNamespaces: "UserAgent" | "ChatAgent";
  }
  interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
