import type { Attachment, ConnectionId, GrantId } from "@cable/core";
import { describe, expect, it, vi } from "vitest";

import { MemoryConnection, MemorySocket } from "./socket.js";

type MutableAttachment = {
  -readonly [Key in keyof Attachment]: Attachment[Key];
};

function connectionId(value: string): ConnectionId {
  // SAFETY: The fixture uses a non-empty connection identifier generated by a Host.
  // oxlint-disable-next-line typescript/no-unsafe-type-assertion -- ConnectionId is a string brand.
  return value as ConnectionId;
}

function grantId(value: string): GrantId {
  // SAFETY: The fixture uses a non-empty grant identifier generated by the engine.
  // oxlint-disable-next-line typescript/no-unsafe-type-assertion -- GrantId is a string brand.
  return value as GrantId;
}

function attachment(): MutableAttachment {
  return {
    cid: connectionId("connection-1"),
    grantId: grantId("grant-1"),
    phase: "pending",
    v: 1,
  };
}

describe("memory socket pair", () => {
  it("dispatches open, message, and close asynchronously", async () => {
    const operations: (() => Promise<void> | void)[] = [];
    const socket = new MemorySocket((operation) => operations.push(operation));
    const messages: unknown[] = [];
    const states: string[] = [];
    socket.addEventListener("open", () => states.push("open"));
    socket.addEventListener("message", (event) => messages.push(event.data));
    socket.addEventListener("close", () => states.push("close"));
    socket.accept({
      close: async () => undefined,
      message: async () => undefined,
      terminate: () => undefined,
    });

    expect(socket.readyState).toBe(0);
    await operations.shift()?.();
    expect(socket.readyState).toBe(1);
    const connection = new MemoryConnection(
      connectionId("connection-1"),
      ["cid:connection-1"],
      attachment(),
      socket,
      () => undefined,
    );
    connection.send("frame");
    expect(messages).toEqual([]);
    await operations.shift()?.();
    expect(messages).toEqual(["frame"]);

    socket.close(1_000, "done");
    expect(socket.readyState).toBe(2);
    await operations.shift()?.();
    expect(states).toEqual(["open", "close"]);
    expect(socket.readyState).toBe(3);
  });

  it("preserves attachment values and immutable tags", () => {
    const socket = new MemorySocket((operation) => void operation());
    const initial = attachment();
    const connection = new MemoryConnection(
      connectionId("connection-1"),
      ["cid:connection-1"],
      initial,
      socket,
      () => undefined,
    );
    initial.phase = "ready";

    expect(connection.tags).toEqual(["cid:connection-1"]);
    expect(connection.attachment.get()).toEqual({
      cid: "connection-1",
      grantId: "grant-1",
      phase: "pending",
      v: 1,
    });
  });

  it("terminates without invoking the server close callback", () => {
    const onClose = vi.fn<() => void>();
    const socket = new MemorySocket((operation) => void operation());
    socket.accept({
      close: async () => undefined,
      message: async () => undefined,
      terminate: onClose,
    });
    socket.terminate();

    expect(onClose).toHaveBeenCalledOnce();
    expect(socket.readyState).toBe(3);
  });

  it("enforces the runtime attachment limit on every write", () => {
    const socket = new MemorySocket((operation) => void operation());
    const initial = attachment();
    const initialBytes = new TextEncoder().encode(JSON.stringify(initial)).byteLength;
    const connection = new MemoryConnection(
      connectionId("connection-1"),
      [],
      initial,
      socket,
      () => undefined,
      initialBytes,
    );

    expect(() =>
      connection.attachment.set({
        ...attachment(),
        since: Number.MAX_SAFE_INTEGER,
      }),
    ).toThrow("Connection attachment exceeds the Host attachment byte limit.");
    expect(connection.attachment.get()).toEqual(attachment());
  });
});
