/* eslint-disable */
// Generated by Wrangler by running `wrangler types env.d.ts --include-runtime false` (hash: 194bbb19cd4962e4d85187798e7d8c28)
declare namespace Cloudflare {
  interface GlobalProps {
    mainModule: typeof import("./src/server");
    durableNamespaces: "PubSubServer";
  }
  interface Env {
    PubSub: DurableObjectNamespace<import("./src/server").PubSubServer>;
  }
}
interface Env extends Cloudflare.Env {}
